// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOycOR8l0-sLeOQQo8PKVaoOfZVB0i19g',
    appId: '1:137975673562:web:58c2d9e27f92580de96be3',
    messagingSenderId: '137975673562',
    projectId: 'deneme-mehmet-a04f4',
    authDomain: 'deneme-mehmet-a04f4.firebaseapp.com',
    storageBucket: 'deneme-mehmet-a04f4.appspot.com',
    measurementId: 'G-117NP0JE94',
    databaseURL: ' ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHTe2zt4sKqw6K7yI_UQv1pAGgc4CctAg',
    appId: '1:137975673562:android:c419142b801b3b08e96be3',
    messagingSenderId: '137975673562',
    projectId: 'deneme-mehmet-a04f4',
    storageBucket: 'deneme-mehmet-a04f4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCm4pYhsQdyrbodTN_7mkZqZFWGDqG4Ts0',
    appId: '1:137975673562:ios:6d579ab86d02af71e96be3',
    messagingSenderId: '137975673562',
    projectId: 'deneme-mehmet-a04f4',
    storageBucket: 'deneme-mehmet-a04f4.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCm4pYhsQdyrbodTN_7mkZqZFWGDqG4Ts0',
    appId: '1:137975673562:ios:30791be58cfe4a1ae96be3',
    messagingSenderId: '137975673562',
    projectId: 'deneme-mehmet-a04f4',
    storageBucket: 'deneme-mehmet-a04f4.appspot.com',
    iosBundleId: 'com.example.flutterApplication1.RunnerTests',
  );
}
